name: Compile Java with `javac`

on: [push]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"

      - name: Compile src
        run: javac src/main/Main.java

      - name: Compilation success
        if : success()
        run: echo "Compilation success"

      - name: Compilation failed
        if : failure()
        run: echo "Compilation failed"
